version: '3.7'

services:

  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start