name: CI
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.17.3

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
              with:
                  node-version: 14.17.3
                  
    - name: Install node.js packages
              run: npm install  
    - name: Run tests and attempt building
      run: npm install

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:ci-build